'impo 1 libsue
IF CURRENTRECORD("USR_LIBSUE_V_NROBLQ") = "04" THEN

A="'"

SSQL = " "
SSQL = SSQL + " SELECT ISNULL(SUM(SJRMVI_CALCUL),0) FROM SJRMVI "
SSQL = SSQL + " INNER JOIN SJRMVH ON SJRMVI_CODFOR = SJRMVH_CODFOR "
SSQL = SSQL + " AND SJRMVI_NROFOR = SJRMVH_NROFOR "
SSQL = SSQL + " AND SJRMVI_TIPLIQ = SJRMVH_TIPLIQ "
SSQL = SSQL + " AND SJRMVI_PERIOD = SJRMVH_PERIOD "
SSQL = SSQL + " AND SJRMVI_NROLEG = SJRMVH_NROLEG "
SSQL = SSQL + " WHERE SJRMVI_CODCPT IN (55000, 55010) "
SSQL = SSQL + " AND SJRMVI_PERIOD = "&PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL
SSQL = SSQL + " AND SJRMVI_NROLEG = "&ACTUALREG("NUMEROLEGAJO")
SSQL = SSQL + " AND SJRMVI_FECALT <= '"&ACTUALREG("FECALT")&A
SSQL = SSQL + " AND SJRMVH_CIERRE = 'S' "
RESULT = queryExec(CSTR(SSQL))

'El imponible 1 informa los conceptos:
'55000    Tope Imponible 1
'55010    Tope Imponible 1 (SAC)

END IF

'impo1 sjccoh cpt 5-5000
BASE_IMPONIBLE = LEGAJO.ACUM("REMUNE")-LEGAJO.ACUM("IMPSAC")
TOPE = LEGAJO.CONCEPTO("VCPT_55000_CONST1")

IF (BASE_IMPONIBLE <= 0) THEN
    RESULT = 0
ELSE
    IF (BASE_IMPONIBLE > TOPE) THEN
        RESULT = TOPE
    ELSE
        RESULT = BASE_IMPONIBLE
    END IF 
END IF
'const1 = 957320.12

'-----------------------------------------------------------------------------------
'impo 4 libsue
IF CURRENTRECORD("USR_LIBSUE_V_NROBLQ") = "04" THEN

A="'"

SSQL = " "
SSQL = SSQL + " SELECT ISNULL(SUM(SJRMVI_CALCUL),0) FROM SJRMVI "
SSQL = SSQL + " INNER JOIN SJRMVH ON SJRMVI_CODFOR = SJRMVH_CODFOR "
SSQL = SSQL + " AND SJRMVI_NROFOR = SJRMVH_NROFOR "
SSQL = SSQL + " AND SJRMVI_TIPLIQ = SJRMVH_TIPLIQ "
SSQL = SSQL + " AND SJRMVI_PERIOD = SJRMVH_PERIOD "
SSQL = SSQL + " AND SJRMVI_NROLEG = SJRMVH_NROLEG "
SSQL = SSQL + " WHERE SJRMVI_CODCPT IN (55030, 55040) "
SSQL = SSQL + " AND SJRMVI_PERIOD = "&PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL
SSQL = SSQL + " AND SJRMVI_NROLEG = "&ACTUALREG("NUMEROLEGAJO")
SSQL = SSQL + " AND SJRMVI_FECALT <= '"&ACTUALREG("FECALT")&A
SSQL = SSQL + " AND SJRMVH_CIERRE = 'S' "
RESULT = queryExec(CSTR(SSQL))

'El imponible 1 informa los conceptos:
'55030	Tope Imponible 4 (obra Social)
'55040	Tope Imponible 4 SAC (obra Social)

END IF

'cpt 55030
OBRA_SOCIAL = LEGAJO.CONCEPTO("CPT_00080")

REMUNERATIVO = LEGAJO.ACUM("REMUNE")-LEGAJO.ACUM("IMPSAC")
NO_REMUNERATIVO = LEGAJO.ACUM("NOREMU")
TOPE = LEGAJO.CONCEPTO("VCPT_55030_CONST1")
TIPLIQ = LEGAJO.CONCEPTO("VLIQ_TIPLIQ")

IF (TIPLIQ = "MC") THEN
    ESCALA_SALARIAL = LEGAJO.CONCEPTO("VCPT_55030_CONST3")
    BASE_IMPONIBLE = ESCALA_SALARIAL + NO_REMUNERATIVO
ELSE

    IF (OBRA_SOCIAL = 126205) THEN
        IF (TIPLIQ = "MM") THEN
            BASE_IMPONIBLE = (REMUNERATIVO+NO_REMUNERATIVO)*2
        ELSE
            BASE_IMPONIBLE = REMUNERATIVO+NO_REMUNERATIVO
        END IF
    ELSE
        IF (TIPLIQ = "MM") THEN
            BASE_IMPONIBLE = REMUNERATIVO*2
        ELSE
            BASE_IMPONIBLE = REMUNERATIVO
        END IF
    END IF

END IF

'Comparacion con tope final
IF (BASE_IMPONIBLE <= 0) THEN
    RESULT = 0
ELSE
    IF (BASE_IMPONIBLE > TOPE) THEN
        RESULT = TOPE
    ELSE
        RESULT = BASE_IMPONIBLE
    END IF
END IF


'cpt 55040




'-----------------------------------------------------------------------------------

'impo5 libsue
IF CURRENTRECORD("USR_LIBSUE_V_NROBLQ") = "04" THEN
Result = Actualreg("IMPO1")

'El imponible 5 informa la misma base del imponible 1
END IF

