'50010 TOP JUB
A = "'"
Nroleg = A & Legajo.Nroleg & A
Period = Legajo.Peract


SSQL = " "
SSQL = SSQL + " SELECT ISNULL(SUM(SJRMVI_CALCUL),0)  "
SSQL = SSQL + " FROM SJRMVI "
SSQL = SSQL + " WHERE  SJRMVI_MODFOR ='SJ' "
SSQL = SSQL + " AND SJRMVI_CODFOR='L'  "
SSQL = SSQL + " AND SJRMVI_PERIOD= " & Period 
SSQL = SSQL + " AND SJRMVI_NROLEG= " & Nroleg 
SSQL = SSQL + " AND SJRMVI_CODCPT= '50020' "
SSQL = SSQL + " AND (SELECT SJRMVH_CIERRE FROM SJRMVH WHERE SJRMVH_CODFOR = SJRMVI.SJRMVI_CODFOR AND SJRMVH_NROFOR = SJRMVI.SJRMVI_NROFOR AND SJRMVH_NROLEG = SJRMVI.SJRMVI_NROLEG ) = 'S'  "
RESULT = QUERYEXEC(CSTR(SSQL))