'concepto 60000
IF(CPT_55000=0,
        0,IF(CPT_00010=1,
                (Legajo.Acum("BDTDES")+Legajo.Acum("BASJUB"))*VCPT_60000_CONST1,
                    '474530.27       +      0 
                (Legajo.Acum("BDTDES")+Legajo.Acum("BASJUB"))*VCPT_60000_CONST2))

'concepto 50050
REMUNERATIVO = LEGAJO.ACUM("REMUNE") 'REMUNERATIVO     619596.96
SAC = LEGAJO.ACUM("ACUSAC") 'CONCEPTOS SAC    0
CONSUMIDO = LEGAJO.CONCEPTO("CPT_50000") 'TOPE CONSUMIDO EN EL MES   '0

TOPE = QUERYEXEC(CSTR("SELECT ISNULL(USR_TOPE,0) FROM USR_TOPES_CONTROL_I WHERE USR_CODIGO_I = 'JUBILA' AND USR_CODIGO_H = 'DESLEY'")) 'TOPE JUBILACION

IF (REMUNERATIVO-SAC) > (TOPE-CONSUMIDO)+
 THEN
        619596.96           474530.27
    RESULT = TOPE-CONSUMIDO
ELSE
    RESULT = REMUNERATIVO-SAC
END IF