'CONCEPTO 6-0850
'Formula planilla
IF(VLEG_SISEC="S",Legajo.Acum("SINDIC")*VCPT_60850_CONST1,0)
'Formula VBScript
NOVEDAD = LEGAJO.CONCEPTO("NOVI_60580")
AFILIADO = LEGAJO.CONCEPTO("VLEG_SISEC") 'Si esta afiliado a SEC
ACUM = LEGAJO.ACUM("SINDIC")
CONST1 = LEGAJO.CONCEPTO("VCPT_60850_CONST1")

IF (NOVEDAD <> 0) THEN
    RESULT = NOVEDAD
ELSE
    IF(AFILIADO = "S")THEN
        RESULT = ACUM * CONST1
    ELSE
        RESULT = 0
    END IF
END IF



