'concepto detraccion 80500 solimeno
A = "'"
NROLEG = LEGAJO.NROLEG
MES = LEGAJO.CONCEPTO("VLIQ_MESLIQ")
ANIO = LEGAJO.CONCEPTO("VLIQ_ANOLIQ")
PERIODO = LEGAJO.PERACT
TIPLIQ = LEGAJO.CONCEPTO("VLIQ_TIPLIQ")

'Según análisis en Tk. 11384 la Detracción se tiene que aplicar una vez en el período.
SSQL = " SELECT COUNT(*) FROM SJRMVI " 
SSQL = SSQL + " INNER JOIN SJRMVH ON SJRMVH_PERIOD = SJRMVI_PERIOD AND SJRMVH_NROFOR = SJRMVI_NROFOR AND SJRMVH_TIPLIQ = SJRMVI_TIPLIQ AND SJRMVH_NROLEG = SJRMVI_NROLEG "
SSQL = SSQL + " WHERE SJRMVI_NROLEG = "&NROLEG 
SSQL = SSQL + " AND SJRMVI_PERIOD = "&PERIODO 
SSQL = SSQL + " AND SJRMVI_CODCPT = 80500 "
SSQL = SSQL + " AND SJRMVH_CIERRE = 'S' "
VALIDACION_DETRACCION = QUERYEXEC(CSTR(SSQL))

IF (VALIDACION_DETRACCION > 0) THEN
    RESULT = 0
ELSE

    DETRACCION = LEGAJO.CONCEPTO("VCPT_80500_CONST1")

    SSQL = " SELECT SJMLGA_CODVAL FROM SJMLGA "
    SSQL = SSQL + " WHERE SJMLGA_CODATR = 'CODACT' "
    SSQL = SSQL + " AND SJMLGA_NROLEG = "&NROLEG
    CODACT = QUERYEXEC(CSTR(SSQL))

    FECHA_INGRESO = QUERYEXEC(CSTR("SELECT SJMLGH_FCHING FROM SJMLGH WHERE SJMLGH_NROLEG = "&NROLEG))
    FECHA_INGRESO = A& YEAR(FECHA_INGRESO) & RIGHT("0"&MONTH(FECHA_INGRESO),2) & RIGHT("0"&DAY(FECHA_INGRESO),2) &A

    PRIMER_DIA_MES = A& ANIO & MES & "01" &A

    SSQL = " SELECT DAY(EOMONTH("&PRIMER_DIA_MES&")) "
    DIAS_MES = QUERYEXEC(CSTR(SSQL))

    ULTIMO_DIA_MES = A& ANIO & MES & DIAS_MES &A

    SSQL = " SELECT ISNULL(SUM(DATEDIFF(D,NEWING,NEWEGR)+1),0) FROM "
    SSQL = SSQL + " (SELECT *,"
    SSQL = SSQL + " CASE WHEN SJMLGH_FCHING <= "&PRIMER_DIA_MES&" THEN "&PRIMER_DIA_MES&" ELSE SJMLGH_FCHING END AS NEWING, "
    SSQL = SSQL + " CASE WHEN SJMLGH_FCHEGR >= "&ULTIMO_DIA_MES&" THEN "&ULTIMO_DIA_MES&" ELSE SJMLGH_FCHEGR END AS NEWEGR "
    SSQL = SSQL + " FROM SJMLGH "
    SSQL = SSQL + " WHERE SJMLGH_NROLEG = "&NROLEG
    SSQL = SSQL + " AND SJMLGH_FCHING <= "&ULTIMO_DIA_MES&" AND SJMLGH_FCHEGR >= "&PRIMER_DIA_MES&") AS TABLA "
    CAMPO = QUERYEXEC(CSTR(SSQL))

    IF (CAMPO = 0) THEN
        'Para aquellos legajos que entraron en este mes
        IF (FECHA_INGRESO > PRIMER_DIA_MES AND FECHA_INGRESO <= ULTIMO_DIA_MES) THEN
            'Calculo la diferencia de días entre el ingreso y el último día del mes
            DIAS_TRABAJADOS = QUERYEXEC(CSTR("SELECT DATEDIFF(D,"&FECHA_INGRESO&","&ULTIMO_DIA_MES&")+1"))
        ELSE
            'El legajo trabajó todo el mes
            DIAS_TRABAJADOS = 100
        END IF
    ELSE
        DIAS_TRABAJADOS = CAMPO
    END IF


    IF (DIAS_TRABAJADOS = 100 AND CODACT = 120) THEN
        DETRACCION = DETRACCION*2.5
    ELSE
        IF (DIAS_TRABAJADOS = 100 AND CODACT <> 120) THEN
            DETRACCION = DETRACCION
        ELSE
            IF (DIAS_TRABAJADOS <> 100 AND CODACT = 120) THEN
                DETRACCION = (DIAS_TRABAJADOS/DIAS_MES)*(DETRACCION*2.5)
            ELSE
                DETRACCION = (DIAS_TRABAJADOS/DIAS_MES)*(DETRACCION*2.5)
            END IF
        END IF
    END IF

    REMUNE_LIQ = LEGAJO.ACUM("ACU001") 'Remunerativo de la liq. actual

    SSQL = " SELECT SUM(CASE SUBSTRING(SJRMVI_TIPCPT,1,1) WHEN 'H' THEN SJRMVI_CALCUL "
    SSQL = SSQL + " ELSE 0 END) FROM SJRMVI "
    SSQL = SSQL + " INNER JOIN SJRMVH ON SJRMVH_NROLEG = SJRMVI_NROLEG AND SJRMVH_PERIOD = SJRMVI_PERIOD AND SJRMVH_TIPLIQ = SJRMVI_TIPLIQ AND SJRMVH_MODFOR = SJRMVI_MODFOR AND SJRMVH_CODFOR = SJRMVI_CODFOR AND SJRMVH_NROFOR = SJRMVI_NROFOR "
    SSQL = SSQL + " WHERE SJRMVH_NROLEG = "&NROLEG
    SSQL = SSQL + " AND SJRMVI_PERIOD = "&PERIODO
    SSQL = SSQL + " AND SJRMVH_CIERRE = 'S' "
    SSQL = SSQL + " AND (SJRMVI_TIPLIQ = '"&TIPLIQ&"'"
    SSQL = SSQL + "      OR SJRMVI_TIPLIQ IN "
    SSQL = SSQL + " (SELECT USR_LIBSUE_DATOS_TIPLIQ FROM USR_LIBSUE_DATOS "
    SSQL = SSQL + "  WHERE USR_LIBSUE_DATOS_PERIODO = "&PERIODO
    SSQL = SSQL + "  AND USR_LIBSUE_DATOS_PRESENTADO = 'S')) "
    REMUNE_MES = QUERYEXEC(CSTR(SSQL)) 'Suma de Remunerativo de todo el mes

    REMUNERATIVO = REMUNE_LIQ+REMUNE_MES

    SSQL = "SELECT SJCCOV_IMPORT FROM SJCCOV WHERE SJCCOV_CODCPT = 50100 AND SJCCOV_CODVAR = 'CONST2'"
    TOPEDM = QUERYEXEC(CSTR(SSQL))

    IF ((REMUNERATIVO-DETRACCION) > 0 AND (REMUNERATIVO-DETRACCION) > TOPEDM) THEN
        RESULT = DETRACCION
    ELSE
        IF ((REMUNERATIVO-DETRACCION) > 0 AND (REMUNERATIVO-DETRACCION) < TOPEDM) THEN
            RESULT = REMUNERATIVO-TOPEDM
        ELSE
            RESULT = 0
        END IF
    END IF

END IF