'exposicos 
IF CURRENTRECORD("USR_LIBSUE_V_NROBLQ") = "04" THEN

CUIL = CURRENTRECORD("DOCUMENTO")
CODOBS = MID(CSTR(CURRENTRECORD("CODOBS")),1,6)
IMPJUB = CURRENTRECORD("IMPO1")
CODACT = CURRENTRECORD("CODACT")
AJUSTEJUB=CURRENTRECORD("AJUJUB")
'REMTOT
'RESULT = CURRENTRECORD("REMUNE") + CURRENTRECORD("REMUNE2")
'END IF        2562507.12         + -34110.13         
'               2.528.396,99

'IF CURRENTRECORD("REMTOT") < CURRENTRECORD("IMPO2")  then 
'   2528396,99                      2562507.12
                                   '2562250712
'	REMUNE = CURRENTRECORD("IMPO1")
                    '1157112.83
'ELSE
	'REMUNE = CURRENTRECORD("REMTOT")
'END IF 

'empieza codigo nuevo 2024 Sergio
IF (CURRENTRECORD("REMUNE2")<0) THEN 
    REMUNE = CURRENTRECORD("IMPO2")
ELSE
    REMUNE = CURRENTRECORD("REMTOT")
END IF
'termina codigo nuevo 2024
SSQL = "SELECT SJMLGI_SELECC from SJMLGI where SJMLGI_CODVAR = 'CONCCT' AND "
SSQL = SSQL + "SJMLGI_NROLEG = "&NROLEG
CONCONV = QUERYEXEC(CSTR(SSQL))
IF(CONCONV="S") THEN
CONCONV = 1
ELSE
CONCONV = 0
END IF

CORRED = PARAMETERS("MARCCRED").VALUES(1).FROMVALUESQL
IF CORRED = "'S'" THEN
    CORRED = 1
ELSE
    CORRED = 0
END IF

CODEMP = PARAMETERS("CODEMPASOCTRABJ").VALUES(1).FROMVALUETEXT

REMTOTA= CURRENTRECORD("REMTOT")

ASIGNA = CURRENTRECORD("ASIGNA")
HIJOS = CURRENTRECORD("HIJOS")
ESPOSA = CURRENTRECORD("CONYU")
ADI = CURRENTRECORD("REPARTO")
CODZON = CURRENTRECORD("CODZON")
CODSIT = CURRENTRECORD("CODSIT")
CODCON = CURRENTRECORD("CODCON")
MODCON = CURRENTRECORD("MODCON")
NOMBRE =  mid(CURRENTRECORD("NOMBRE"),1,30)
NOMBRE = Replace(NOMBRE,"ñ","n")
NOMBRE = Replace(NOMBRE,"Ñ","N")


NOMBRE = Replace(NOMBRE,"á","a")
NOMBRE = Replace(NOMBRE,"é","e")
NOMBRE = Replace(NOMBRE,"í","i")
NOMBRE = Replace(NOMBRE,"ó","o")
NOMBRE = Replace(NOMBRE,"ú","u")

NOMBRE = Replace(NOMBRE,"Á","A")
NOMBRE = Replace(NOMBRE,"É","E")
NOMBRE = Replace(NOMBRE,"Í","I")
NOMBRE = Replace(NOMBRE,"Ó","O")
NOMBRE = Replace(NOMBRE,"Ú","U")

NOMBRE = Replace(NOMBRE,"¥","N")

SSQL = "SELECT SUM(SJRMVI_CALCUL) FROM SJRMVI WHERE"
SSQL = SSQL + " SJRMVI_NROLEG = "&CURRENTRECORD("NUMEROLEGAJO")
SSQL = SSQL + " AND SJRMVI_PERIOD = '"&PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL
SSQL = SSQL + "' AND SJRMVI_CLAEMP= "&PARAMETERS("CLAEMP").VALUES(1).FROMVALUESQL
SSQL = SSQL + " AND SJRMVI_CODCPT = '44001'"

CPT_44001 = QUERYEXEC(CSTR(SSQL))

SSQL = "SELECT SUM(SJRMVI_CALCUL)*-1 FROM SJRMVI WHERE"
SSQL = SSQL + " SJRMVI_NROLEG = "&CURRENTRECORD("NUMEROLEGAJO")
SSQL = SSQL + " AND SJRMVI_PERIOD = '"&PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL
SSQL = SSQL + "' AND SJRMVI_CLAEMP= "&PARAMETERS("CLAEMP").VALUES(1).FROMVALUESQL
SSQL = SSQL + " AND SJRMVI_CODCPT = '61005'"

CPT_61005 = QUERYEXEC(CSTR(SSQL))

CODOBS2 = MID(CSTR(CURRENTRECORD("CODOBS2")),1,6)
IMPO1 =  CURRENTRECORD("IMPO1")
IMPO2 =  CURRENTRECORD("IMPO2")
IMPO3 =  CURRENTRECORD("IMPO3")
IMPO4 =  CURRENTRECORD("IMPO4")
IMPO5 =  CURRENTRECORD("IMPO5")
IMPO8 =  CURRENTRECORD("IMPO8")
IMPO9 = CURRENTRECORD("IMPO9")
IMPO10 = CURRENTRECORD("IMPO10")

IF IMPO8 < IMPO4 THEN 
	IMPO8 = IMPO4
END IF 

IMPO8 = IMPO8 - CPT_44001

IF IMPO1 > CURRENTRECORD("REMTOT")  THEN 
	IMPO1 =  IMPO2 
	IMPO5 =  IMPO2
END IF 


CADOS =  CURRENTRECORD("CAOS")
PROV =  CURRENTRECORD("PROV")
RG =  CURRENTRECORD("REG")
CON =  CURRENTRECORD("CONV")
ADEOBS = CURRENTRECORD("ADEOBS")
SEGVID = CURRENTRECORD("SEGURO_VIDA")

IF IMPO5 = 0  THEN 
	IMPO1 = 0.01
	IMPO2 = 0.01
	IMPO3 = 0.01
	IMPO4 = 0.01
	IMPO5 = 0.01	
	IMPO8 = 0.01	
END IF 

IF IMPO1 < IMPO5 THEN 
	IMPO1 = IMPO5
END IF 
	

DC_HORAS = CURRENTRECORD("HORAS_DC") 
CANT_HORAS  = CURRENTRECORD("CANT_HE") 
DC_SUELDO  = REMUNE
DC_ZONA =   CURRENTRECORD("ZONA")
DC_BASICO = CURRENTRECORD("BASICO_DC")
IF DC_BASICO  < 0 THEN 
	DC_BASICO  = 0 
END IF 
DC_PREMIO = CURRENTRECORD("PREMIO_DC") 
DC_SAC = CURRENTRECORD("SAC")  
DC_VACAC = CURRENTRECORD("VACAC_DC") 
NOREMU = ACTUALREG("REMUNE2")

DC_SUELDO = DC_SUELDO  - (DC_HORAS + DC_BASICO + DC_PREMIO + DC_SAC + DC_VACAC + DC_ZONA + NOREMU )

IF DC_SUELDO < 0 THEN 
	DC_SAC = DC_SAC + DC_SUELDO
	DC_SUELDO = 0
 END IF 

 IF  CURRENTRECORD("DIAS")  = 100 THEN
	 D = 30
 ELSE
	 D = CURRENTRECORD("DIAS")
 END IF

MES =  MID(CSTR(PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL),5,2)

 IF CINT(MES) = 2 AND D = 30 THEN 
	D = 28 
END IF  

IF (CINT(MES) = 1 OR   CINT(MES) = 3 OR CINT(MES) = 5  OR CINT(MES) = 7 OR CINT(MES) = 8  OR CINT(MES) = 10  OR  CINT(MES) = 12)  and D = 30 THEN 
	D =  31
END IF 

IF D = 0 THEN 
       HS = 1
ELSE 
      HS = 0
END IF 

IF MES = 1 OR  MES = 3 OR MES = 5  OR MES = 8 OR MES = 10 OR MES = 12 THEN 
	DIAS_MAY = 31
ELSE 
 	IF MES = 2   THEN 
		DIAS_MAY = 20
	ELSE
		DIAS_MAY = 30
	END IF 
END IF



 SIT1="01"
 DIA1="01"
 SIT2="00"
 DIA2="00"
 SIT3="00"
 DIA3="00"

IF CODSIT = "02" OR CINT(CODSIT) = 2 THEN 
	CODSIT = "01"
END IF 


IF CODSIT = "13" THEN 
	SIT1 = "13"
END IF 


IF CODSIT = "5" THEN 
	SIT1 = "05"
	CODSIT = "05"
END IF 

IF CODSIT=18 THEN

	SINI="01"

ELSE

	SINI = "00"

END IF

'CALCULO EL REMUNERATIVO DE LAS DIFERENTES LIQUIDACIONES DEL MES
SSQL = " SELECT SUM(CASE SUBSTRING(SJRMVI_TIPCPT,1,1) WHEN 'H' THEN SJRMVI_CALCUL ELSE 0 END) FROM SJRMVI "
SSQL = SSQL + " INNER JOIN SJRMVH ON SJRMVH_NROLEG = SJRMVI_NROLEG AND SJRMVH_PERIOD = SJRMVI_PERIOD AND SJRMVH_TIPLIQ = SJRMVI_TIPLIQ AND SJRMVH_MODFOR = SJRMVI_MODFOR AND SJRMVH_CODFOR = SJRMVI_CODFOR AND SJRMVH_NROFOR = SJRMVI_NROFOR "
SSQL = SSQL + " WHERE SJRMVH_NROLEG = "&CURRENTRECORD("NUMEROLEGAJO")
SSQL = SSQL + " AND SJRMVI_PERIOD = "&PARAMETERS("PERIODO").VALUES(1).FROMVALUESQL
SSQL = SSQL + " AND SJRMVH_CIERRE = 'S' "
AUXREMUNE = QUERYEXEC(CSTR(SSQL))

'SSQL = "SELECT SJCCOV_IMPORT FROM SJCCOV WHERE SJCCOV_CODCPT = 50100 AND SJCCOV_CODVAR = 'CONST2'"
'TOPEDM = QUERYEXEC(Cstr(SSQL)) Se comenta segun Tk. 11415

MONDETRAER = IMPO10 

IF MODCON = "15" OR MODCON = "17" OR MODCON = "49" Then
	MONDETRAER = 0
	IMPO10 = 0
ELSE
	'IF AUXREMUNE - IMPO10 > 0  AND AUXREMUNE - IMPO10 > TOPEDM Then
		MONDETRAER = IMPO10
		IMPO10 = (IMPO2 - MONDETRAER)
	'ELSE
		'IF AUXREMUNE - IMPO10 > 0  AND AUXREMUNE - IMPO10 < TOPEDM Then 
		'	MONDETRAER = AUXREMUNE - TOPEDM
		'	IMPO10 = (IMPO2 - MONDETRAER)
		'ELSE
		'	MONDETRAER = 0
		'	IMPO10 = 0
		'END IF
	'END IF
END IF


IF SIT1 = 5 OR SIT2 = 5 OR SIT3 = 5 OR SIT1 = 11 OR SIT2 = 11 OR SIT3 = 11 THEN

MATER = REMUNE

ELSE 

MATER = 0

END IF

X_RESULT = CURRENTRECORD("USR_LIBSUE_V_NROBLQ") & (CUIL) & C_NUMERO(ESPOSA,1,0) &  MID(CSTR(C_NUMERO(HIJOS,2,0)),1,2) & C_NUMERO(CONCONV,1,0) & SEGVID &C_NUMERO(CORRED,1,0)
X_RESULT = X_RESULT & C_NUMERO(CODEMP,1,0) & C_NUMERO(0,1,0) & C_STRING(CODSIT,2)&C_STRING(CODCON,2)&C_NUMERO(CODACT,3,0)&C_NUMERO(MODCON,3,0)&C_NUMERO(SINI,2,0)
X_RESULT = X_RESULT & C_NUMERO(CODZON,2,0)&C_NUMERO(SIT1,2,0)&C_NUMERO(DIA1,2,0)&C_NUMERO(SIT2,2,0)&C_NUMERO(DIA2,2,0)&C_NUMERO(SIT3,2,0)&C_NUMERO(DIA3,2,0)
X_RESULT = X_RESULT & C_NUMERO(D,2,0)&C_NUMERO(HS,3,0)&C_NUMERO(ADI,5,2)&C_NUMERO(0,5,2)&(CODOBS)&C_NUMERO(ADEOBS,2,0)&C_NUMERO(0,15,2)
X_RESULT = X_RESULT & C_NUMERO(0,15,2)&C_NUMERO(0,15,2)&C_NUMERO(0,15,2)&C_NUMERO(0,15,2)&C_NUMERO(MATER,15,2)&C_NUMERO(REMUNE,15,2)&C_NUMERO(IMPO1,15,2)
X_RESULT = X_RESULT & C_NUMERO(IMPO2,15,2)&C_NUMERO(IMPO3,15,2)&C_NUMERO(IMPO4,15,2)&C_NUMERO(IMPO5,15,2)&C_NUMERO(0,15,2)&C_NUMERO(0,15,2)&C_NUMERO(IMPO8,15,2)
X_RESULT = X_RESULT & C_NUMERO(IMPO9,15,2)&C_NUMERO(0,15,2)&C_NUMERO(0,15,2)&C_NUMERO(IMPO10,15,2)&C_NUMERO(MONDETRAER,15,2)

RESULT = X_RESULT


    FUNCTION C_NUMERO(CAMPO,LARGO, DECIMALES)
    CAMPO= REPLACE(CAMPO, "*", "")
    AUXNUMERO=FORMATNUMBER(CAMPO,DECIMALES,,,0)
    AUXNUMERO= REPLACE(AUXNUMERO, ".", "")
    IF INSTR(AUXNUMERO,"-") <> 0 THEN
        AUXNUMERO= REPLACE(AUXNUMERO, "-", "")
        C_NUMERO= "-" &STRING((LARGO-1) - LEN(TRIM(AUXNUMERO)),"0") & TRIM(AUXNUMERO)
    else
        C_NUMERO= STRING(LARGO - LEN(TRIM(AUXNUMERO)),"0") & TRIM(AUXNUMERO)
    END IF
    END FUNCTION


FUNCTION C_STRING(CAMPO,LARGO)
C_STRING= TRIM(CAMPO) & STRING(LARGO - LEN(TRIM(CAMPO))," ") 
END FUNCTION


FUNCTION C_DERECHA(CAMPO,LARGO)
C_DERECHA=STRING(LARGO - LEN(TRIM(CAMPO))," ") &TRIM(CAMPO) 
END FUNCTION


END IF


