'CONCEPTO OBRA SOCIAL

A = "'"
NOVEDAD = LEGAJO.CONCEPTO("NOVI_60100")

SIN_DESCUENTO = LEGAJO.CONCEPTO("VLEG_SINDES")      'No realiza los descuentos de Ley (N)
SINDICATO_SEC = LEGAJO.CONCEPTO("VLEG_SINSEC")      'Sindicato SEC (N)
CONDICION = LEGAJO.CONCEPTO("CPT_00020")            'Condición de Contratación AFIP (1.0)
ACTIVIDAD_AFIP = LEGAJO.CONCEPTO("CPT_00010")       'Código de Actividad AFIP (1.0)
CODIGO_OBRA_SOCIAL = LEGAJO.CONCEPTO("CPT_00050")   'Código Obra Social	(400909.00)
IMPONIBLE_4_ANTERIORES = LEGAJO.CONCEPTO("CPT_50110") '0 No aparece ne la tabla de sql
IMPONIBLE_4 = LEGAJO.CONCEPTO("CPT_50250")            'Imponible 4	1157112.83
IMPONIBLE_4_SAC_ANTERIORES = LEGAJO.CONCEPTO("CPT_50115")  '0
IMPONIBLE_4_SAC = LEGAJO.CONCEPTO("CPT_50450")         '0

PORCENTAJE_OBRA_SOCIAL = LEGAJO.CONCEPTO("VCPT_60100_CONST1")*-1    '-0.03      Obra Social	-34713.38
DESCUENTOS_OBS_ANTERIORES = LEGAJO.CONCEPTO("CPT_60099")            '0

TIPOLIQ = LEGAJO.CONCEPTO("VLIQ_TIPLIQ") 'M

'---------------------------CÁLCULO DE DÍAS TRABAJADOS----------------------------------------------------------
NROLEG = LEGAJO.NROLEG '643
ANIO = LEGAJO.CONCEPTO("VLIQ_ANOLIQ") '2024
MES = RIGHT("0"&LEGAJO.CONCEPTO("VLIQ_MESLIQ"),2) '01

PRIMER_DIA_MES = A& ANIO&MES&"01" &A ' '20240101'
ULTIMO_DIA = QUERYEXEC(CSTR("SELECT DATEPART(DD,EOMONTH("&PRIMER_DIA_MES&"))")) '31
ULTIMO_DIA_MES = A& ANIO&MES&ULTIMO_DIA &A '20240131

CPT_DIAS_TRABAJADOS = LEGAJO.CONCEPTO("CPT_00101") 'DÍAS TRABAJADOS SEGÚN CONCEPTO 00101 (30.0)

'SI EL CONCEPTO 00101 DEVUELVE VALOR, UTILIZO ESOS DÍAS PARA EL PRORRATEO DEL PISO. EN CAMBIO, EN OTRAS LIQUIDACIONES, ESTE CONCEPTO NO SE CALCULA ASÍ QUE UTILIZO LA ANTIGUEDAD SEGÚN LA SOLAPA DEL LEGAJO
IF (CPT_DIAS_TRABAJADOS <> 0) THEN
    DIAS_TRABAJADOS = CPT_DIAS_TRABAJADOS
ELSE
    SSQL = " "
    SSQL = " SELECT ISNULL(SUM (DATEDIFF(D,"
    SSQL = SSQL + " CASE WHEN SJMLGH_FCHING <= "&PRIMER_DIA_MES&" THEN "&PRIMER_DIA_MES&" ELSE SJMLGH_FCHING END,"
    SSQL = SSQL + " "&ULTIMO_DIA_MES&")),0)+1"
    SSQL = SSQL + " FROM SJMLGH WHERE SJMLGH_NROLEG = "&NROLEG&" AND SJMLGH_CHKEGR = 'N'"
    
    DIAS_TRABAJADOS = QUERYEXEC(CSTR(SSQL)) 'DÍAS TRABAJADOS SEGÚN INGRESO (EL CONCEPTO 00101 YA LO HACE PERO PARA CIERTAS LIQUIDACIONES NO SE CALCULA)
END IF 'devuelve 30 dias
'---------------------------------------------------------------------------------------------------------------



'METODO DE CALCULO---------------------------------------------------------------------------------------------

IMPOSAC_NR = LEGAJO.ACUM("BASOSA") 'CONCEPTOS DE SAC NO REMUNERATIVOS QUE DEBEN INCLUIRSE
IMPOSAC = LEGAJO.ACUM("IMPOSA") 'CONCEPTOS DE SAC REMUNERATIVOS 

NO_REMUNERATIVO = LEGAJO.ACUM("BASOS2") 'CONCEPTOS NO REMUNERATIVOS PARA OBRA SOCIAL
REMUNERATIVO = LEGAJO.ACUM("REMUNE") - IMPOSAC 'PARA LOS IMPONIBLES NORMALES NO TOMO EN CUENTA CONCEPTOS REMUNERATIVOS QUE SEAN DE SAC

'SI LA LIQUIDACIÓN TIENE SÓLO CONCEPTOS NORMALES Y NO TIENE DE SAC (LIQUIDACIÓN NORMAL) CALCULO SÓLO LOS VALORES DE LIQUIDACIONES NORMALES.
IF ((REMUNERATIVO <> 0 OR NO_REMUNERATIVO <> 0) AND (IMPOSAC = 0 AND IMPOSAC_NR = 0)) THEN

    BASE_IMPONIBLE_4_COMPARACION = IMPONIBLE_4_ANTERIORES + IMPONIBLE_4

ELSE

    'SI LA LIQUIDACIÓN NO TIENE CONCEPTOS NORMALES Y SÓLO TIENE DE SAC (LIQUIDACIONES DE AGUINALDO O FINALES SIN CONCEPTOS REMUNERATIVOS), CALCULO SÓLO VALORES DE LIQUIDACIONES SAC.
    IF ((REMUNERATIVO = 0 AND NO_REMUNERATIVO = 0) AND (IMPOSAC <> 0 OR IMPOSAC_NR <> 0)) THEN

        BASE_IMPONIBLE_4_COMPARACION = IMPONIBLE_4_SAC_ANTERIORES + IMPONIBLE_4_SAC

    ELSE 'SI LA LIQUIDACIÓN TIENE CONCEPTOS NORMALES Y TAMBIÉN TIENE DE SAC, CALCULO TODOS LOS VALORES JUNTOS

        BASE_IMPONIBLE_4_COMPARACION = IMPONIBLE_4_ANTERIORES + IMPONIBLE_4 + IMPONIBLE_4_SAC_ANTERIORES + IMPONIBLE_4_SAC

    END IF

END IF

FINAL = ((BASE_IMPONIBLE_4_COMPARACION * PORCENTAJE_OBRA_SOCIAL) - DESCUENTOS_OBS_ANTERIORES)*-1 


IF SIN_DESCUENTO = "S" OR CONDICION = 2 OR (CONDICION = 2 AND ACTIVIDAD_AFIP = 48) THEN
	FINAL = 0
END IF 


IF (NOVEDAD <> 0) THEN
	RESULT = NOVEDAD
ELSE
    'Se coloca siguiente validación por si el descuento llega a dar centavos
    IF (ABS(FINAL) < 1) THEN
	    RESULT = 0
    ELSE
	    RESULT = FINAL
    END IF
END IF